In [1]:
import numpy as np

In [2]:
ls=[1,2,3]
arr=np.array(ls)
type(arr)

numpy.ndarray

In [3]:
arr.ndim

1

In [4]:
arr.size

3

In [5]:
arr.shape

(3,)

In [7]:
# create array with integer and floating value

l1=[2,3,4,3.4,3.4]
arr1=np.array(l1)

In [8]:
arr1

array([2. , 3. , 4. , 3.4, 3.4])

In [9]:
np.array([2,3,4,55,4.4,4.3,43.3],dtype='int')

array([ 2,  3,  4, 55,  4,  4, 43])

In [15]:
data = np.array([
    [12, 43, 23, [12, 43, 23], 3],
    [12, 42, 22, [12, 43, 23], 32],
    [12, 42, 22, [12, 43, 23], 32]
], dtype=object)

In [13]:
data.ndim

2

In [17]:
data=np.array([[12,23],[23,45],[45,np.nan]])
data

array([[12., 23.],
       [23., 45.],
       [45., nan]])

In [18]:
data=np.array([[12,23],[23,45],[45,None]])
data

array([[12, 23],
       [23, 45],
       [45, None]], dtype=object)

In [19]:
list(range(1,11))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [20]:
list(range(1.5,11.5))

TypeError: 'float' object cannot be interpreted as an integer

In [21]:
np.arange(1.5,11.5)

array([ 1.5,  2.5,  3.5,  4.5,  5.5,  6.5,  7.5,  8.5,  9.5, 10.5])

In [22]:
np.arange(1.5,11.5,2)

array([1.5, 3.5, 5.5, 7.5, 9.5])

In [25]:
data=np.array([[12,23,3],[23,45,4]])
data

array([[12, 23,  3],
       [23, 45,  4]])

In [26]:
data.reshape(3,2)

array([[12, 23],
       [ 3, 23],
       [45,  4]])

In [27]:
data.reshape(1)

ValueError: cannot reshape array of size 6 into shape (1,)

In [29]:
data.reshape(6,1)

array([[12],
       [23],
       [ 3],
       [23],
       [45],
       [ 4]])

In [30]:
data=np.array([[[12,23,3],[23,45,4]]])
data

array([[[12, 23,  3],
        [23, 45,  4]]])

In [33]:
data.flatten() #-> it use to convert n dimensional array into one dimension array

array([12, 23,  3, 23, 45,  4])

In [34]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [36]:
np.ones([2,3])

array([[1., 1., 1.],
       [1., 1., 1.]])

In [37]:
np.zeros([2,3,4])

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [38]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [40]:
np.random.randint(1,10,5)

array([5, 5, 4, 2, 9], dtype=int32)

In [41]:
np.random.rand(1,10,5)

array([[[0.91839599, 0.59476501, 0.73692224, 0.97958594, 0.00236248],
        [0.13609658, 0.93912166, 0.3399514 , 0.33997605, 0.3250925 ],
        [0.2757333 , 0.18717459, 0.79849022, 0.45694808, 0.52401162],
        [0.40155176, 0.79021273, 0.78734695, 0.41707044, 0.32577653],
        [0.79748843, 0.47277364, 0.86547208, 0.01697672, 0.21278705],
        [0.59342408, 0.93625045, 0.81418347, 0.28067503, 0.63134221],
        [0.64799973, 0.45121861, 0.65381405, 0.66281298, 0.89173568],
        [0.30997396, 0.99659538, 0.31747673, 0.02824665, 0.24239013],
        [0.11819908, 0.10467333, 0.74739925, 0.67939581, 0.82215986],
        [0.5705092 , 0.57299235, 0.03202089, 0.67194932, 0.70114202]]])

In [42]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [44]:
arr=np.arange(1,11).reshape(2,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [45]:
new_arr=arr.view()
new_arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [46]:
arr[0][0]=100
arr

array([[100,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10]])

In [47]:
new_arr

array([[100,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10]])

In [48]:
new_arr1=arr.copy()

In [50]:
arr[0][0]=1100
arr


array([[1100,    2,    3,    4,    5],
       [   6,    7,    8,    9,   10]])

ModuleNotFoundError: No module named 'matplotlib'